@baseUrl = http://localhost:5171

### Autenticação
# Endpoints relacionados à autenticação
GET {{baseUrl}}/api/auth
Accept: application/json

### Eventos
# Endpoints relacionados a eventos
GET {{baseUrl}}/api/eventos
Accept: application/json

### Tags
# Endpoints relacionados a tags
GET {{baseUrl}}/api/tags
Accept: application/json

### Usuários
# Endpoints relacionados a usuários
GET {{baseUrl}}/api/usuarios
Accept: application/json

### Ministérios
# Endpoints relacionados a ministérios
GET {{baseUrl}}/api/ministerios
Accept: application/json

### Voluntários
# Endpoints relacionados a voluntários
GET {{baseUrl}}/api/voluntarios
Accept: application/json